### ISSUE TITLE
no se= for factor scores with categorical indicators

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#151]
Is this a known limitation?

```
HS9 <- HolzingerSwineford1939[,c("x1","x2","x3","x4","x5",
                                 "x6","x7","x8","x9")]
HSbinary <- as.data.frame( lapply(HS9, cut, 2, labels=FALSE) )
HS.model <- ' visual  =~ x1 + x2 + x3
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '
fit <- cfa(HS.model, data=HSbinary, ordered=names(HSbinary))
lavPredict(fit, se = "standard") # error
```

If so, I can add a check with a better error message, and add it to the help-page description.

**Comment by yrosseel** [comment]
There are indeed no SEs available (yet) when data is categorical. But this should only produce a warning, not an error. Fixed in 0.6-5. (The standard errors for categorical data will not be added in the near future; this will be part of a much bigger update involving support for MML and non-normal data).
