### ISSUE TITLE
Getting Incorrect Estimates only Some of the time

### ISSUE THREAD

**Issue by sumphatguy** [yrosseel/lavaan#162]
EDIT at end.

Hi Yrosseel!

I have been trying out the lavaan package for some CFA an SEM modeling. I have run into a very strange issue where R gives me incorrect results only some of the time. I have been comparing the output to SPSS AMOS to make sure it is correct.

The issue I am having is that I get incorrect output based on the number of observations I am using, and I have narrowed it down to how the package is utilizing the covariance matrix. I have attached two files with covariance matrices. The "fullCov" is from the full sample of 210 observations and gives me incorrect output. The "subCov" is from a subsample of 199 observations and gives me correct output. I have tried recreating the covariance matrices in other programs as well to see if it is related to R creating the matrix, and I still get the same results.

This is the model I am testing:
BNS.model <- 'autonomy =~ BNSW_1 + BNSW_5 + BNSW_8 + BNSW_11 + BNSW_13 + BNSW_17 + BNSW_20
              competence =~ BNSW_3 + BNSW_4 + BNSW_10 + BNSW_12 + BNSW_14 + BNSW_19
              relatedness =~ BNSW_2 + BNSW_6 + BNSW_7 + BNSW_9 + BNSW_15 + BNSW_16 + BNSW_18 + BNSW_21'

The third file I attached has the estimates that I expect to get followed by the estimates I get from R utilizing the full 210 observations.

Anyway, I am not sure how to fix this. If I am doing something incorrectly, please let me know. Oh, and I have been testing this using the Mimic="EQS" option as well and still get incorrect results. I also considered rounding to be an issue, but the results are too far off to just be because of rounding.

_sumphatguy

Edit: I was able to get the correct values by specifying "start = 'simple'" Can anyone explain why this would change so much?

[estimates.xlsx](https://github.com/yrosseel/lavaan/files/3698640/estimates.xlsx)
[fullCov.xlsx](https://github.com/yrosseel/lavaan/files/3698641/fullCov.xlsx)
[subCov.xlsx](https://github.com/yrosseel/lavaan/files/3698642/subCov.xlsx)

**Comment by TDJorgensen** [comment]
Please provide an R script that fits your model to your data, so we do not have to guess what is in your "estimates" file.  I assume they are factor loadings, and from your first paragraph I gather that your only criterion for concluding results are somehow "incorrect" is that they don't match Amos output.  What makes you think Amos is "correct"?  (That's just a rhetorical question.)

If using different starting values leads to different estimates, that suggests empirical underidentification. Your _N_ is too small for 21 variables (i.e., 21(22)/2 = 231 unique elements in the covariance matrix, larger than your _N_), so empirical underidentification would not be a surprise. 

Even if you had a large sample relative to the number of parameters in your model, if you obtain very different covariance matrices between the full _N_ and _N_-11 samples, that suggests you have either some influential outliers or very nonnormal data. In either case, you should analyze your raw data, not covariance matrices, so that you can use estimators robust to nonnormality (available in `lavaan`) or to outliers (available in the `regsem` package).

**Comment by yrosseel** [comment]
I had a look at this, and it turns out that the 'AMOS' estimates (or the ones you obtain with start = "simple") are a local minimum (X2 = 1424.061); the lavaan estimates result in a X2 = 1311.136).
