### ISSUE TITLE
MIMIC 

### ISSUE THREAD

**Issue by pdldeepen** [yrosseel/lavaan#186]
I am trying to estimate unobserved economy using MIMIC model. I
thmodel = '
 c =~ TO + GDPPC + UR + SG + FF + RL + CC + GS
 i =~ CIC + LFP + CG
 
 c ~~ pi*i
 '
thfit = sem(thmodel, sample.cov = data.cov, sample.nobs = 187)

But I am getting error message
Error in lav_model_estimate(lavmodel = lavmodel, lavpartable = lavpartable,  : 
  lavaan ERROR: initial model-implied matrix (Sigma) is not positive definite;
  check your model and/or starting parameters.
How can i solve this problem
[DataT.xlsx](https://github.com/yrosseel/lavaan/files/4872157/DataT.xlsx)

**Comment by yrosseel** [comment]
(This is not a MIMIC model (yet), as there are no covariates in the model.)

Did you compute data.cov based on these 17 observations? In that case, you may wish to rescale SG so that its variance is (say) < 100. But SG correlates 0.98 with CIC, and 0.94 with GS, resulting in an correlation/covariance matrix that is almost singular. If I fit the model on the corelation matrix, the correlation between the latent variables is 1.0...

In lavaan dev 0.6-7.1575, extreme large variances (in sample.cov=) will now trigger a warning.
