### ISSUE TITLE
Information from @SampleStats is wrong?

### ISSUE THREAD

**Issue by mverdam** [yrosseel/lavaan#187]
I wanted to check some observed scores by extracting them from the lavaan output, but it seems that the information stored is not the correct information (or in the correct order), and I cannot find out what is / or I am doing / wrong. Any suggestions??

I am running a multi-group model, based on the full data (running it with cov/means did not solve the problem)
I extract the means for a specific group from [OUTPUT]@SampleStats@mean[[2]]
But the order is wrong (I changed the order of the variables in my dataset, but it doesn't solve the problem)
The first five observations match the first five (baseline) means, but then the first observation from the next five means (from followup) is suddenly the last observation, which changes the order of all the follow-up means (and thus the calculation of difference scores; what I was after). And I wonder whether this influences my results too.

Do you know why the order is different? And if so, whether it also influences results? And if so, how can I fix this? 

Thanks for your help! :)

**Comment by TDJorgensen** [comment]
> Any suggestions?

A general suggestion is to use `lavInspect(fit, "mean.ov")` rather than dig into the internal structure of the lavaan object. The internal structure is not expected to be stable, changing in response to continued development (e.g., categorical data in version 0.5, multilevel data in version 0.6). But the output returned by `lavInspect()` is intended to be stable, regardless of how the internal structure of a lavaan object might change.  If there is an option you want that is not available in the `?lavInspect` list of `what=` options, then it can be requested.

> Do you know why the order is different?

The order of variables is typically determined by the order in which parameters appear in the model syntax.  Given the standard way to specify multigroup models is to specify a single model that applies to both, it would be surprising to see different orders of variables across groups.  Do they appear in different orders when you run `lavNames()`?

```
lavNames(fit, group = 1)
lavNames(fit, group = 2)
```

If you are specifying each group's model separately, then perhaps that explains when variable order can differ across groups.  Or maybe I am misinterpreting: are you just saying that the order of repeatedly measured variables differs between the baseline and follow-up sets?  Again, the order of variables should be determined by their appearance in the model syntax (nothing to do with their appearance in raw data or summary stats).  For example:

```
HS.model <- ' group: 1
  visual  =~ x1 + x2 + x3 # same order as in raw data
  group: 2
  visual  =~ x3 + x1 + x2 # different order, arbitrary, identical estimates as:
  # visual  =~ x1 + x2 + x3
'
fit <- cfa(HS.model, data = HolzingerSwineford1939, group = "school", std.lv = TRUE)
fit@SampleStats@mean # same order as lavInspect
lavInspect(fit, "mean.ov")
## also same order (within each group) as below:
lavNames(fit, group = 1)
lavNames(fit, group = 2)
```

If I am misunderstanding the issue you are trying to describe, it could help to provide a reproducible example that illustrates the issue.

**Comment by mverdam** [comment]
Hi Terrence! Thanks! That helps! 

It was indeed the order of the parameter specification that was different than I assumed. With the @SampleStats you don't get to see the labels, but with the lavInspect you do, so that was insightful. 

I didn't know you could get the observed data from lavInspect too I only used it before for extracting the parameter estimates.
