### ISSUE TITLE
Silent Summary

### ISSUE THREAD

**Issue by dbaranger** [yrosseel/lavaan#193]
This is perhaps a minor issue, but there appears to be no way to silence the output of 'summary()' when the referenced object is from lavaan. For instance, if I try to assign the output of summary to an object for easy reference (eg. J<-summary(fit)), the output of 'summary' is still printed to the console. This quickly becomes a nuisance when running simulations and fitting them with lavaan. This is the only package where I've encountered this sort of behavior. Is there a way to silence 'summary()'?

**Comment by TDJorgensen** [comment]
lavaan's `summary()` method is essentially a 1-stop-shop to print the output of other dedicated functions.  If you don't want to print something to the screen in your simulation, you can instead save the output of the functions that are called by the `summary()` method:

- `parameterEstimates()`
- `fitMeasures()`
- `modIndices()`

**Comment by dbaranger** [comment]
Thanks for the fast and helpful reply. I'll just note that this behavior is unlike any other instance of `summary()` that I know of, so it is confusing for new users.

**Comment by TDJorgensen** [comment]
I agree, but also note that SEMs are unlike other classes of (almost exclusively univariate) model objects in R.  Take care also that you do not expect lavaan's `fitted()` method to be redundant with its `predict()` method when no `newdata=` are provided.

**Comment by yrosseel** [comment]
If I could rewrite lavaan, summary() would indeed be silent if the result is assigned to another object. I will try to achieve this in the future, when I rewrite most of lavaan's internals for 0.7 (god knows in which year this will happen).

(The history of this is that lavaan (when it was written 10 years ago) was targeted at non-R users, with different expectations.)

**Comment by WillemSleegers** [comment]
I would like to second a silent `summary()` function. I'm trying to add support for `lavaan` to my `tidystats` package, which consists of taking the output of `lavaan()`, `cfa()`, or `sem()` and then extracting the statistics from the object. To do this, I need to have the model object and apply the `summary()` function to it, under the hood. I can't use the other functions such as `fitMeasures()` since they don't return an identifiable object (i.e., a `lavaan` object). 

I realize this is my problem but it would be nice to have `lavaan` behave like other functions.

**Comment by yrosseel** [comment]
In 0.6-12, summary() is silent if the output is assigned to an object.
