### ISSUE TITLE
lavaanify(auto.th = TRUE) does not seem to do anything

### ISSUE THREAD

**Issue by cjvanlissa** [yrosseel/lavaan#214]
Lavaanify has an argument auto.th = TRUE, but there does not seem to be a way to pass in names of ordinal variables or their number of thresholds.

**Comment by TDJorgensen** [comment]
It is funny that there is an `auto.th=` argument in `lavaanify()`, since without a `data=` argument, I cannot imagine a way for the function to guess how many thresholds are needed.  So I think you currently need to specify each threshold in the syntax.  But doing so automatically frees them, unless they are fixed in the specification, so indeed, I am curious why the `auto.th=` argument is included here.

FEATURE REQUEST: Perhaps `auto.th=` could be supplemented by a `nThr=` argument (similar role as `ngroups=`), which could be a named `integer` vector indicating both

- which variables are ordinal, via `names(nThr)`
- how many thresholds each ordered variable has

For example, `nThr = c(x1 = 1, x2 = 3, x3 = 4)` could indicate 1, 3, and 4 thresholds for variables x1, x2, and x3, respectively.  This mechanism for indicating ordered variables could also allow `lavaanify()` to correctly fix their scaling factors or residual variances to 1, depending on the `parameterization=` argument.  Currently, specifying a threshold automatically adds both (with starting values of 1):

```
lavaanify('x1 | t1')
```

```
  id lhs  op rhs user block group free ustart exo label plabel
1  1  x1   |  t1    1     1     1    1     NA   0         .p1.
2  2  x1  ~~  x1    0     1     1    0      1   0         .p2.
3  3  x1 ~*~  x1    0     1     1    0      1   0         .p3.
```

**Comment by cjvanlissa** [comment]
Dear Terrence,

yes, I agree. With the added suggestion that, since a correctly specified data set would already contain information about which variables are ordinal and how many categories there are (i.e., every ordered factor), the function should take defaults directly from the data.

**Comment by yrosseel** [comment]
The auto.* arguments originally truly added these parameters (setting them free), while they were not added if set to FALSE. 

Later (since 0.5-18), lavaanify() would always add 'necessary' parameters (like variances, thresholds, scaling parameters), but only set them free if auto.* = TRUE. Otherwise, they are fixed to zero. This is still true for auto.th = FALSE. It may be useful if you have binary items, and you wish to fix the thresholds to zero.

If auto.th = TRUE, the information about the ordered variables, and the number of categories is currently taken from the varTable= argument in lavaanify(). In fact, that is (currently) the only use for varTable in lavaanify(). If we would have a nThr argument (or something similar), we could remove the varTable= argument. But I am not sure if there is need for this. Maybe for simulation purposes? Of settings where there is no data?

**Comment by yrosseel** [comment]
I added a 'nthresholds' argument to the lavaanify() function in 0.6-12. It does not replace varTable. In fact, it can only be used if varTable = NULL. The argument nthresholds can be a single integer, and then all the (endogenous) variables of the model are assumed to be ordered, and the number of thresholds is the same for all ordered variables. Or (as suggested by Terrence) the nthresholds argument can be a named vector, and only those variables will then be treated as ordered, with the given thresholds per variable.

I did not follow the suggestion to also remove either the variances or scaling parameters. This is (in my mind) related to a more general question: should we include 'unused' parameters in the parameter table, or not. The difficulty is that we only know if a parameter is unused (or not needed) for sure if the parameter table (including potential constraints) is complete.
