### ISSUE TITLE
Change the parameters in lavaan fit object

### ISSUE THREAD

**Issue by fartist** [yrosseel/lavaan#224]
Hi,

I was wondering if there is an easy way to change parameter estimates in the fitted lavaan object?

For example, if I wanted to change one estimated parameter from 1 to 2 and recalculate its fit bic etc, is there way to do it efficiently in lavaan? thanks in advance!

**Comment by TDJorgensen** [comment]
Can you explain the context a bit more, to guide the best solution to your problem?  Are you writing a function to automate some kind of statistic where this would be useful behavior?

In the simplest case, you can save the `parTable()` output, save estimates as starting values, set the `$est` and `$se`  columns to `NULL`, and set the whole `$free` column to `0` to indicate all parameters are fixed.  Then you can change whatever parameter you want in the (u)start column(s) and pass the parameter table (instead of model syntax) to `lavaan()`. Without estimating anything, you aren't "fitting" the model, so you have to tell `lavaan` to lie to you with the argument `optim.force.converged = TRUE`  (see the `?lavOptions` help page).

```
example(cfa)
PT <- parTable(fit)
PT$ustart <- PT$est # use estimates as starting values
PT$est <- NULL
PT$se <- NULL
PT$start <- NULL
PT$free <- 0L # fix all parameters
PT$ustart[2] <- 3.14 # change a parameter value
## re"fit" the model
summary(update(fit, model = PT, optim.force.converged = TRUE))
```

**Comment by yrosseel** [comment]
Yep. That is the only way.
