### ISSUE TITLE
A couple questions about lavaan output

### ISSUE THREAD

**Issue by meenachakra** [yrosseel/lavaan#227]
Thank you for developing this excellent package. We used the lavaan function of your package. Specifically, while assessing the effect of a one week intervention on depression, we did a path analysis to see whether the change from baseline to week 1 in psychosocial outcomes such as accomplishment and stress (input) predict change in depression scores between weeks 1 and 6.

We then got a p-value for each coefficient in the resulting model (P(>|z|)). We were wondering: (1) whether these p-values need to be adjusted for multiple comparisons equalling the number of coefficients; (2) what it means if our model test user model "test statistic" is 0; and (3) how many variables you think it's reasonable to include for a sample size of 45. We are hopeful to hear back from you. Thank you again.

**Comment by ecmerkle** [comment]
These questions are probably better suited to the lavaan google group, instead of the github issues (and you might get more opinions in the google group). But, since I'm here:

(1) It probably depends on what you plan to do with the p-values. Personally, I would not think about adjusting them unless my paper hinged on one or two significant coefficients. But I would also look at magnitude of coefficients and standard errors, vs just the p-values.

(2) This typically means that the model is "just identified", e.g., you have as many free parameters as data points (where "data points" would often be "number of covariances between observed variables").

(3) A sample size of 45 is fairly small for SEM. I don't think there is a single rule of thumb here, but the free book below offers lots of good advice and strategies:

https://doi.org/10.4324/9780429273872

**Comment by meenachakra** [comment]
Thank you! This is very helpful. Really appreciate your reply.
