### ISSUE TITLE
use different chisq in fitMeasures() 

### ISSUE THREAD

**Issue by TDJorgensen** [yrosseel/lavaan#253]
Is it possible to add a `type=` argument to `fitMeasures()`, which could be passed to `lavTest()` in order to calculate chi-squared-based fit indices with Browne's statistic?  In those cases, it might not make sense to return the scaled stats, but we never finished that conversation.  Perhaps also a `scaled=` argument which can be set FALSE.  Not sure what the best design choice would be...

**Comment by yrosseel** [comment]
This is now possible with 0.6-13.1798 or higher. Several changes have been made:
- a global option "scaled.test" determines the test statistic that gets 'scaled' by for example the Satorra-Bentler correlation; the default is "standard", but if could also be, say, "browne.residual.nt"; only a single test statistic can be scaled, but multiple scaling methods are possible; see also lavTest()
- the fit.args() argument in fitmeasures() has been renamed to fm.args()
- fm.args = list(standard.test = "browne.residual.nl") can be used to change the main test statistic (ie chi-square value) that is the basis of many fit measures; this also affects the test statistic used in the baseline model
- fm.args = list(scaled.test = "scaled.shifted") can be used to change the scaling method that is used for the scaled fit measures; it can also be set to "none" to avoid printing them
The options are part as list elements of a single fm.args() argument in order to avoid adding more options to the summary() method for lavaan objects (which also accepts the fm.args() argument).
