### ISSUE TITLE
Changing arrangement of variables changes results when ordered

### ISSUE THREAD

**Issue by die-zeitgeist** [yrosseel/lavaan#271]
Hi,
In lavaan_0.6-15, when I declare my data as continuous changing arrangement of variables gives the same chi-square and other fit measures for different variable orders. When I declare variables as ordered different arrangements gives different results. 

Here is the reproducible example: 
 
[ordered_data.csv](https://github.com/yrosseel/lavaan/files/11020764/ordered_data.csv)

`library(lavaan)

one_factor_model <-'one_factor=~m1+m2+m3+m4+m5+m6+m7+m8+m9+m10+m11+m12+m13+m14+m15+m16+m17+m18+
m19+m20+m21+m22+m23+m24+m25+m26+m27+m28'

results1<-cfa(one_factor_model, ordered_data, ordered=TRUE)

summary(results1, fit.measures=TRUE)`

gives 
`lavaan WARNING:
    the optimizer warns that a solution has NOT been found!`

but when I change the place of m1 such as place it as last variable or third variable lavaan gives correct results. Example below:

`library(lavaan)

one_factor_model <-'one_factor=~m28+m2+m3+m4+m5+m6+m7+m8+m9+m10+m11+m12+m13+m14+m15+m16+m17+m18+
m19+m20+m21+m22+m23+m24+m25+m26+m27+m1'

results1<-cfa(one_factor_model, ordered_data, ordered=TRUE)

summary(results1, fit.measures=TRUE)`  

Note: I think it is related with the selection of variable as the calibration item but it doesn't happen when it is continuous. Thank you

**Comment by yrosseel** [comment]
I don't think there is bug here. It is just the case that when m1 is the 'marker' indicator, the optimizer fails to find a solution for this model/data combination. BTW, It will work if you add the bounds = "standard" option.

The reason why it doesn't work (out-of-the-box) with m1 as the marker indicator is that m1 is negatively correlated with most other indicators. Reversing the sign so that all correlations (within the same factor) are positive is usually a good idea to improve convergence.
