### ISSUE TITLE
Lavaan Users Google Group Erroneously Banned: no extra documentation is currently available

### ISSUE THREAD

**Issue by hmswaffles** [yrosseel/lavaan#371]
When I check the Lavaaan Users Group, it has been erroneously banned by Google. None of the  This is likely the result of an automated process. I'm submitting this as an issue b/c Yves and Terrance are traveling through August. Is anyone else an owner of the group? If so, they can appeal this. 

Here is a screenshot of what I see: 

<img width="1016" alt="Screenshot 2024-07-16 at 12 51 40 PM" src="https://github.com/user-attachments/assets/304071e9-f8c4-4894-9b98-3a62286c3981">

**Comment by TDJorgensen** [comment]
We are aware. Yves got the email from Google that he can pursue legal action if he wants. The problem is that the past few days there were literally hundreds of spam posts. In the past we would sometimes get 5-10, which I took the time to flag as spam, one by one. But somehow the group got bombed by a bot, and Google's software just flagged the group automatically. 

We asked for help from an ally on the group who is a Google employee, and he has initiated a conversation on our behalf. No guarantees, but in the meantime, StackExchange is a more secure platform to post questions, and there are R and lavaan flags you can add to your post.

**Comment by yrosseel** [comment]
As of 31 July 2024, the lavaan discussion group is back.
