### ISSUE TITLE
"tcrossprod" is not a BUILTIN function for sem()

### ISSUE THREAD

**Issue by AMOS0024** [yrosseel/lavaan#390]
I keep getting this error:
Error in tcrossprod(EV$vectors/rep(EV$values, each = length(EV$values)),  : 
  "tcrossprod" is not a BUILTIN function

My code:
M1.fit <- sem(M1.model, sample.cov = covq1, sample.nobs = 194)
summary(M1.fit, fit.measures=TRUE)
standardizedsolution(M1.fit)

**Comment by yrosseel** [comment]
Just in case others have this problem: 

This only happens if you have installed a binary version of lavaan (or any other package for that matter). The problem occurs when you are using an older version of R, compared to the version of R that was just to 'compile' the R package. Because crossprod() and tcrossprod() became primitive functions recently, recent binary packages (using those two functions) are no longer compatible with older version of R.

There are 2 solutions:

1) update R to the most recent version
2) install lavaan from source:

`install.packages("lavaan", type = "source")`
