### ISSUE TITLE
Warning when comparing measurement invariance models using 'anova'

### ISSUE THREAD

**Issue by erikson84** [yrosseel/lavaan#66]
I'm trying to compare models to assess measurement invariance with ordinal indicator variables. In the first model, all parameters are free to vary between groups; the second model restrains the loadings to be equal. In the second model, all loadings are free to be estimated (via NA in the model syntax) and the lv metric is set to one in the reference group.

But, when I try to compare both models via the 'anova' function, I get the following warning:
Warning message:
In lav_partable_constraints_ceq(P0, txtOnly = TRUE) :
  lavaan WARNING: non-free parameter(s) in equality constraint(s): .p1. .p7.

Both (internal) parameter refer to the loadings of the first indicator variables, but the syntax explicitly frees them (via 'NA') and adds the constraint (via parameter label). The LR table shows both DF and Chisq for both models, but offers no information on model comparison. If I simply free both parameters but don't constrain them, the model comparison displays as expected.

I tried to investigate and noticed that, when I estimate the first indicator parameter and constrain it, the 'lav_partable_constraints_ceq' function (or rather, the function that calls it, lav_test_diff_af_h1) returns this function:

```
function (.x., ...) 
{
    out <- numeric(0L)
    .p1. <- NA
    .p7. <- NA
    .p2. <- .x.[1]
    .p3. <- .x.[2]
    .p4. <- .x.[3]
    .p5. <- .x.[4]
    .p6. <- .x.[5]
    .p8. <- .x.[6]
    .p9. <- .x.[7]
    .p10. <- .x.[8]
    .p11. <- .x.[9]
    .p12. <- .x.[10]
    out[1] <- .p1. - (.p7.)
    out[2] <- .p2. - (.p8.)
    out[3] <- .p3. - (.p9.)
    out[4] <- .p4. - (.p10.)
    out[5] <- .p5. - (.p11.)
    out[6] <- .p6. - (.p12.)
    out[7] = .x.[78] - 1
    return(out)
}
<environment: 0x7609ce8>
```

But if I fit the model without the constraint, the function has no 'NA's:

```
function (.x., ...) 
{
    out <- numeric(0L)
    .p2. <- .x.[1]
    .p3. <- .x.[2]
    .p4. <- .x.[3]
    .p5. <- .x.[4]
    .p6. <- .x.[5]
    .p8. <- .x.[6]
    .p9. <- .x.[7]
    .p10. <- .x.[8]
    .p11. <- .x.[9]
    .p12. <- .x.[10]
    out[1] <- .p2. - (.p8.)
    out[2] <- .p3. - (.p9.)
    out[3] <- .p4. - (.p10.)
    out[4] <- .p5. - (.p11.)
    out[5] <- .p6. - (.p12.)
    out[6] = .x.[78] - 1
    return(out)
}
<environment: 0x8b8d658>
```

And, indeed, if I call the lavTestLRT function with parameter A.method='delta', the Chisq Diff is computed.

Thanks,
Erikson

**Comment by yrosseel** [comment]
I investigated this, and it turns out that the key problem is that the restricted (h0) model is not fully nested (in the parameter sense) in the larger (h1) model: h0 frees the factor loadings of p1 and p7, while they are fixed to 1 in h0.

This piece of code (from lav_test_diff_af_h1) fails to take that into account:

 PT.M0.part1$free[p0.free.idx] <-
    PT.M1.part1$free[ PT.M0.part1$id[p1.id][p0.free.idx] ]

(the free factor loadings in h1 become nonfree as they are overwritten by the corresponding parameters in h0)

Unfortunately, this is not easy to fix. Currently, I consider making A.method='delta' the default, until a much more robust version of lav_test_diff_af_h1() becomes available.

In the mean time, I will keep this issue 'open'.

**Comment by yrosseel** [comment]
A.method = "delta" is now the default in 0.6-2.
