### ISSUE TITLE
Negative Satorra-Bentler (2010) difference test due to problem with starting values for M10

### ISSUE THREAD

**Issue by falkcarl** [yrosseel/lavaan#81]
I can get the "strictly positive" robust difference test of Satorra & Bentler (2010) to go negative (see attached). When I look at the result of line 227 or so of lav_test_diff.R, it looks as though m10 is not properly using the starting values from M0 (i.e., PE.M0.extended) even though it is specified as the "start" argument. I've seen this happen recently before in some of my other work. If both "model" and "start" arguments are specified and "model" happens to be a parameter table with certain columns (e.g., "est"), then the "start" argument appears to have no effect.

[SB2010Negative.pdf](https://github.com/yrosseel/lavaan/files/1040215/SB2010Negative.pdf)

**Comment by falkcarl** [comment]
And apparently satorra.bentler.2010 worked fine in Version 0.5-20 (according to Jordan Brace; also confirmed by me), so something must have broken since then...

**Comment by yrosseel** [comment]
It was only broken in 0.5-23. The reason was the introduction of the '...' in the lavaan() function call, to replace the ever growing list of options (see also lavOptions()). Now, when the slotOptions= argument was used, all other options (including 'start') in the lavaan() function call were silently ignored. This was the case in lav_test_diff.R. 

Fixed now in dev 0.6-1.1144
